### ISSUE TITLE
destroy() not being called on Linux

### ISSUE THREAD

**Issue by mgree** [cberner/fuser#153]
I'm using fuser on macOS and Linux. My filesystem writes data back out when `destroy()` is called, which works fine on macOS. On Linux, it seems like `destroy()` is never getting called.

This issue may be old: https://github.com/zargony/fuse-rs/issues/151. Others have had issues with libfuse not properly calling destroy due to [signal handlers](https://github.com/libfuse/libfuse/issues/228).

You can see a [successful run on macOS](https://github.com/mgree/ffs/runs/2843591862?check_suite_focus=true#step:5:185); the relevant ["calling sync" lines](https://github.com/mgree/ffs/blob/ec7e63e129ad1a41ee37e4b9a54178747130d60b/src/fs.rs#L185-L189) don't appear [on Linux](https://github.com/mgree/ffs/runs/2843591890?check_suite_focus=true#step:5:40).

I had suspected that calling `fusermount -u` instead of `umount` was the key, but it [makes no difference](https://github.com/mgree/ffs/runs/2843898103?check_suite_focus=true#step:5:280). Killing the process [doesn't help either](https://github.com/mgree/ffs/runs/2843928635?check_suite_focus=true#step:5:278).

**Comment by mgree** [comment]
A workaround (in mgree/ffs#8): I use `Drop::drop` instead of `Filesystem::destroy` to write my output.

**Comment by cberner** [comment]
Thanks for the report. Ya, I can confirm that I don't see `destroy` called. I'm looking into whether it works with a naive C filesystem built with libfuse

**Comment by mgree** [comment]
Awesome---thanks for the super fast turnaround on this! 🎉 

Glancing at the change log in #154, am I right to understand that the contract with `destroy()` is that it will be called _exactly_ once?

**Comment by cberner** [comment]
Yes, it should now be called exactly once, and no other methods should be called after `destroy()`

**Comment by mgree** [comment]
I just upgraded ffs to fuser 0.9.1, but I'm getting some weird behaviors on Linux---notably that `destroy` isn't getting called, and I'm now getting an OS error when `drop` is called.

You can see an example in my [CI logs](https://github.com/mgree/ffs/runs/3704411391?check_suite_focus=true#step:5:1121), where there's no log from [destroy](https://github.com/mgree/ffs/blob/138aed54f072bf95860a56b67b4c3a3d9a49298f/src/fs.rs#L366-L369) and on os error 14 (EFAULT, bad address).

Any idea what could be going wrong here?

**Comment by cberner** [comment]
Hmm, can you check if this line prints in your log, with logging enabled? https://github.com/cberner/fuser/blob/master/src/session.rs#L180

Also, are you mounting the filesystem with `mount` or `spawn_mount`?

**Comment by mgree** [comment]
[I am not getting the unmount print in my logs](https://github.com/mgree/ffs/runs/3708188009?check_suite_focus=true#step:5:60).

I'm using [`mount2` to mount things](https://github.com/mgree/ffs/blob/fuser-0.9.1/src/main.rs#L37). There's some weirdness, there, too: [I get a `fusermount` warning about an option I'm not using](https://github.com/mgree/ffs/runs/3708188009?check_suite_focus=true#step:5:68).

**Comment by mgree** [comment]
I [tried a run where I don't do anything in `drop` and only use `destroy`](https://github.com/mgree/ffs/runs/3708253435?check_suite_focus=true#step:5:68), and you can see that even there `destroy` isn't being called.

I haven't dug into fuser code yet, but could it be that the reference to my `FS` isn't living long enough, and it's getting dropped before the call to `destroy` gets made?

**Comment by mgree** [comment]
Oh, in fact: that `fusermount` error was the core issue. If you look at the ubuntu logs, it seems like `FS` is dropped right after the `fusermount` error. Apparently [fuser is adding `allow_other` because I use autounmount](https://github.com/cberner/fuser/blob/master/src/session.rs#L74-L80).

Here's the `/etc/fuse.conf` GitHub CI is giving me (it's all defaults):

```
# /etc/fuse.conf - Configuration file for Filesystem in Userspace (FUSE)

# Set the maximum number of FUSE mounts allowed to non-root users.
# The default is 1000.
#mount_max = 1000

# Allow non-root users to specify the allow_other or allow_root mount options.
#user_allow_other
```

The new logic in https://github.com/cberner/fuser/commit/0009aa184b9c91fbeacb6f364d28571192af70ae adds the `allow_other` option, which my config doesn't allow. Turning off `autounmount` [seems to solve the problem](https://github.com/mgree/ffs/runs/3708348951?check_suite_focus=true).

Would you accept a PR that gave a user-facing warning (at warn level) when `allow_other` is automatically added due to `autounmount`?

**Comment by cberner** [comment]
Yep, happy to a merge to PR to add that warning. Thanks for tracking it down!
