### ISSUE TITLE
Unideal error message when not having `user_allow_other`

### ISSUE THREAD

**Issue by hellow554** [cberner/fuser#167]
When having not the option `user_allow_other` set in `/etc/fuse.conf` the following message appears:

```
fusermount: option allow_other only allowed if 'user_allow_other' is set in /etc/fuse.conf
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 0, kind: Other, message: "Success" }', examples/null.rs:11:68
```

Please note the code and message which is not ideal.

Is there something we could do to get a better error message?

**Comment by cberner** [comment]
The easy fix is to check for that flag in your application before mounting the filesystem. For example, like this: https://github.com/cberner/fuser/blob/e30eb1d06612f78cacc6207c25d61845562bfd09/examples/simple.rs#L1938-L1946

**Comment by Profpatsch** [comment]
I get the same error when I pass `fuser::MountOption::AutoUnmount`. Why is that? something libfuse-specific?
