### ISSUE TITLE
Support splice()

### ISSUE THREAD

**Issue by cberner** [cberner/fuser#18]

**Comment by cberner** [comment]
https://github.com/Mic92/cntr-fuse/commit/bb1c89fdc72d312329614758f44924373fd61184

**Comment by cberner** [comment]
Closing. The linked patch isn't related to the splice feature added in ABI 7.14. The feature that was added appears to be a performance optimization that allows libfuse to use splice() when communicating with the kernel

**Comment by ChengCat** [comment]
The linked patch is exactly about the `SPLICE_*` options added in ABI 7.14. `SPLICE_*` allows the performance optimization using the `splice` system call. This performance optimization can be important for some applications.
