### ISSUE TITLE
Add logging to default Filesystem method implementations

### ISSUE THREAD

**Issue by jam1garner** [cberner/fuser#181]
Currently the majority of `Filesystem` methods have a default implementation which simply return an error. That is, of course, desirable behavior as expecting users to implement all these methods from the get-go is silly. However one issue this creates is that when progressively adding new features it can be unclear which unimplemented methods are causing things to fail.

The options currently are:
* Guess and check
* Make copies of all the unimplemented methods with println statements
* Just keep implementing stuff till it works or fails in a new way

I feel the default implementation should log warnings for each unimplemented method which runs, excluding ones which do not return an error by default (for example `init` does not need this as it is truly optional, while `getxattr` should emit a warning before returning `ENOSYS`)

If this such changes are deemed exceptable I'm more than willing to implement/test/PR such changes, just let me know. :)

**Comment by cberner** [comment]
Ya, I'm happy to merge a PR to add that. I think I'd like them to be at `info` level rather than `warn` though. Some filesystems may intentionally not implement some calls, and I'd rather it didn't clutter up the log for those cases. I'm not entirely sure about info vs warn though. Do you know if `libfuse` does any logging for unimplemented operations?

**Comment by jam1garner** [comment]
Afaik libfuse doesn't do any logging of that sort, so there's about 4-5 templates [like this](https://github.com/retrohacker/libfuse-template) for it because it's a pretty common desire. I'll work on a PR tomorrow and go with `info` like you said :+1:

**Comment by cberner** [comment]
@jam1garner I see, `error` like that template uses seems too extreme. I think `debug` actually fits the use case better than `info` for most things, like @boulos suggested, so lets go with that instead. I'd be fine with the basic operations like `getattr` and `read` being `warn` though, if you want to make those more severe. Basically anything that a non-trivial implementation needs to implement being `warn` seems like a good idea to me, but then for the extra features I think `debug` is the best fit.
