### ISSUE TITLE
Some historical issues with this repo and upstream

### ISSUE THREAD

**Issue by unknowndevQwQ** [cberner/fuser#186]
I see in readme.md that this repo is from https://github.com/zargony/fuse-rs fork, and have a question: why did you choose to fork a new repo instead of committing pr

**Comment by cberner** [comment]
I submitted some of my work as a PR: https://github.com/zargony/fuse-rs/pull/130

However, the maintainer has been busy, and I wanted to make changes more quickly, which is why I forked it
