### ISSUE TITLE
[question] Implementing streaming read

### ISSUE THREAD

**Issue by thmey** [cberner/fuser#203]
I am looking for pointers on how to implement FUSE FS for a cloud storage, which does not support the range request HTTP header.

Currently I am stuck in caching the file in a `Vec<u8>` and then passing slices to the FUSE `read` function, which causes `read` to block for the time of the download and then passing the slices immediately.
Preferably I would like to use [`bytes_stream`](https://docs.rs/reqwest/latest/reqwest/struct.Response.html#method.bytes_stream), but it seems like this crates does not support async operations.

**Comment by cberner** [comment]
At the moment, I think the only option would be to download just the beginning of the file, then move the rest of the download to a background thread, and return the beginning. async operations aren't supported in fuser at the moment, and probably won't be for a while

**Comment by thmey** [comment]
@cberner I came up with a working solution using tokio runtime and two channels:
Channel1: (`Sender<number of bytes to download>,` `Receiver<Vec<u8>>`)
Channel2: (`Sender<Vec<u8>>`, `Receiver<number of bytes to download>`)

Then it's basically back and forth between the async context inside of tokio and the sync context inside of `read`.
- Wait for number of bytes to download
- Send number of bytes
- Download bytes, send bytes
- Receive bytes, send new byte request

I usually download ~30mb/s from iCloud and I see the same transfer speed using this method.

**Comment by cberner** [comment]
nice! ya, seems like the right approach
