### ISSUE TITLE
How to set the filesystem to -s (single process) -d (debug) as lib fuse do

### ISSUE THREAD

**Issue by Annazhan** [cberner/fuser#209]
Hi! 
When I check the document of macFUSE, I found there some other options like -s and -d. Currently, I try to implement a simple filesystem with features `touch`, `rm`, `cp`, I am wondering which function I need to implement. So I want to make the fuse into single thread for better debug and see what is really going on here.  Is there anyway I can do that?

Thank you so much!

**Comment by cberner** [comment]
Please check the examples. They should show you how to do that: https://github.com/cberner/fuser/tree/master/examples

**Comment by Annazhan** [comment]
Oh! right, I have learned that example, and I found the `MountOption` we use is actually related to `-o` with sub-option in fuse, but it seems that fuse kernel has other options like `-d` and `-s`. Is there any way to add those `-d` and `-s` options using this crate?
