### ISSUE TITLE
Support for auto_cache and kernel_cache

### ISSUE THREAD

**Issue by leakingtapan** [cberner/fuser#213]
I'm looking at libfuse but couldn't find equivalent to auto_cache and kernel_cache, is this supported by fuser?

**Comment by hopkings2008** [comment]
The same question about these two cache options, when can they be supported?

**Comment by ccope** [comment]
I believe these are features of the high-level client, which is not currently available in this crate: #220

**Comment by cberner** [comment]
Correct. You will need to implement your own caching.
