### ISSUE TITLE
Is there a good reason to `parse_options_from_args` as  a `pub(crate)` and not as a `pub` ?

### ISSUE THREAD

**Issue by ahmed-masud** [cberner/fuser#216]
https://github.com/cberner/fuser/blob/3fb6586aaf2e4ef3162c59ae798728a1dcf41eee/src/mnt/mount_options.rs#L161

Would be nice to have this available outside :-) as it builds out `MountOption` reasonably nicely.

**Comment by cberner** [comment]
Yes, that is only there for backwards compatibility with old versions of this crate. I plan to remove it in the future, and so don't want to make that format public.
