### ISSUE TITLE
libfuse high level bindings

### ISSUE THREAD

**Issue by rapiz1** [cberner/fuser#220]
[libfuse](https://github.com/libfuse/libfuse) offers two APIs: a "high-level", synchronous API, and a "low-level" asynchronous API. The current fuser offers bindings to the latter one and works with inodes. However, that's not particularly convenient for simple fs.

Is there any plan for the high level API binding? That would be very useful.

**Comment by cberner** [comment]
Not at this time. fuser is mainly in maintenance mode at the moment.
