### ISSUE TITLE
simple.rs appears to diverge from libfuse spec

### ISSUE THREAD

**Issue by InnovativeInventor** [cberner/fuser#227]
In simple.rs, `read()` appears to return a buf of exactly the number of bytes read:

https://github.com/cberner/fuser/blob/6b76fd1f9cc8caef0ffa057f3e0879c940c9aab8/examples/simple.rs#L1393-L1399

However, this is the correct behavior *only* if the `direct_io` mount option is specified. 
> Read should return exactly the number of bytes requested except on EOF or error, otherwise the rest of the data will be substituted with zeroes. An exception to this is when the 'direct_io' mount option is specified, in which case the return value of the read system call will reflect the return value of this operation. 

(http://libfuse.github.io/doxygen/structfuse__operations.html#a2a1c6b4ce1845de56863f8b7939501b5)

I could be missing something here. Is fuser keeping track of this under the hood somehow?

**Comment by wfraser** [comment]
I don't think this behavior diverges from that text. The language `return exactly the number of bytes requested` matches what `read_exact_at` does: it fills the whole buffer provided (i.e. the number of bytes requested) unless it can't due to hitting an error or the file is too small to fill it (i.e. reached EOF).

The note about `direct_io` is saying that's the one case where you're allowed to return a smaller buffer even when not at EOF, but that's not what's being done here.

I think fuse's comment isn't using the most clear wording, but I'm having a hard time interpreting it any other way than this.

**Comment by InnovativeInventor** [comment]
> I don't think this behavior diverges from that text. The language `return exactly the number of bytes requested` matches what `read_exact_at` does: it fills the whole buffer provided (i.e. the number of bytes requested) unless it can't due to hitting an error or the file is too small to fill it (i.e. reached EOF).

You are right that `read_exact_at` fills the whole buffer that is provided. However, the size of the buffer that is provided is explicitly *not the number of bytes that is requested*. See:
https://github.com/cberner/fuser/blob/6b76fd1f9cc8caef0ffa057f3e0879c940c9aab8/examples/simple.rs#L1393-L1397

If I'm understanding this code correctly, `read_size` is the *minimum* of the bytes requested and the number of bytes til the end of the file. `read_size` is then used to create the buffer. It looks like, based on line 1395, the size of the buffer returned will differ from the number of the bytes requested.

I think we have the same interpretation of the `direct_io` sentence. I read it as (paraphrasing here): "generally, you should return a buffer of the size requested. However, when `direct_io` is specified, you can return a smaller buffer."

Hopefully I'm not missing something obvious here :), I am happy to be corrected.

**Comment by cberner** [comment]
> If I'm understanding this code correctly, `read_size` is the _minimum_ of the bytes requested and the number of bytes til the end of the file. `read_size` is then used to create the buffer. It looks like, based on line 1395, the size of the buffer returned will sometimes differ from the number of the bytes requested.

Yes, which is the correct behavior as I understand the libfuse documentation. It says, "Read should return exactly the number of bytes requested except on EOF". Which is exactly what the code does. It returns the number of bytes requested, unless the file is too short (i.e. EOF)

**Comment by InnovativeInventor** [comment]
@cberner The second half of that sentence says "otherwise the rest of the data will be substituted with zeroes". That sounds to me like the rest of the buffer size should be zeroed out on EOF, rather than shortened. 

The next sentence makes it clear that not zeroing out the rest of the buffer (that is, the current behavior) is ok when the `direct_io` mount option is specified.

**Comment by cberner** [comment]
Hmm ya, I can see it either way. Have you found a bug that the current implementation causes?
