### ISSUE TITLE
write data len always 4096

### ISSUE THREAD

**Issue by exFalso** [cberner/fuser#252]
Hello,

We have a custom fuse filesystem implemented using fuser, and I'm looking into performance optimizations. One of the bottlenecks seems to be that on writes the Filesystem always receives small chunks of size 4096, never anything larger. Things I tried:
* `max_write=` option (even though default is 16M it seems..)
* `config.set_max_write` in `init()`
* `max_pages=256`, `big_writes` (with fuse 2), `direct_io` options
* mount with root (I noticed that fuse behaves differently)

none of it to any avail. Is there something obvious I'm missing? We're using standard options, default features (libfuse)

**Comment by GermanCoding** [comment]
Just a guess, but have you checked whether you are properly requesting `FUSE_BIG_WRITES`? This appears to be only enabled by default if you are increasing the minimum ABI version (i.e. not the default features). https://github.com/cberner/fuser/blob/a9ddc8a7a8cd9f2ba6e7c3bc4c6a76ecad66e6b2/src/lib.rs#L52-L56

**Comment by exFalso** [comment]
Thank you, that was it, with a recent abi version we're getting 128k writes!
