### ISSUE TITLE
Simple example is incorrect

### ISSUE THREAD

**Issue by inferiorhumanorgans** [cberner/fuser#260]
Readlink should return the symlink target path, not the contents of the symlink target.

**Comment by majewsky** [comment]
Are you saying that the implementation should resolve the symlink target into the final path? If so, do you have any reference to back up that claim?

I had a quick look around: The libfuse docs describe "readlink" as "Read the target of a symbolic link" which could be interpreted either way, whereas the documentation for the readlink syscall in `man 2 readlink` is very clear about the behavior from the example being correct.

> readlink() places the contents of the symbolic link `pathname` in the buffer

Besides that, the implication that FUSE filesystems should do final path resolution also seems incredibly unlikely, given that this would run into pathological cases with infinite loops. Only the kernel would have all the information required to stop infinitely recursing symlinks from taking down the entire system.

**Comment by Vogtinator** [comment]
I guess the confusion is because readlink returns the content of the metadata file within `/tmp/fuser/contents/<inode>`, which is the symlink target.
