### ISSUE TITLE
Looking for more examples of fuser usage.

### ISSUE THREAD

**Issue by cpratt34** [cberner/fuser#278]
Hey there! Thanks for putting together this repo, its been very helpful for me diving further into FUSE applications.

I was wondering if you knew of any interesting open source libraries using this crate? The `simple.rs` example file has been very helpful so far, and I'm looking for more content like this to learn from.

A "showcase" section in the readme with a list of some projects using this library would be helpful to myself and others jumping into this space!

**Comment by cberner** [comment]
You can see all the downstream dependencies on crates.io
https://crates.io/crates/fuser/reverse_dependencies

**Comment by cpratt34** [comment]
I keep forgetting about how discoverable the rust ecosystem is. Thanks for the pointer!
