### ISSUE TITLE
Update open flags from u32 to i32

### ISSUE THREAD

**Issue by siscia** [cberner/fuser#76]
Hello,

thanks for the work you are doing forking this library.

The open call get as input the flag argument as `u32`, is there a reason for this?

https://github.com/cberner/fuser/blob/abe89ccd62be4b680ec0c4e1ff918afee2b478be/src/lib.rs#L271

I will be in favor to update that to a `i32` to match the C (int) and Rust interface (i32).

I can submit a PR if this will help in getting this API fix in.

**Comment by cberner** [comment]
Can you provide a reference to the C & Rust interfaces you're referring to for `i32`? I looked up the definition in the kernel source code, which I believe is definitive, and it's declared `uint32_t`: https://elixir.bootlin.com/linux/v5.10-rc1/source/include/uapi/linux/fuse.h#L593

**Comment by siscia** [comment]
Aw, that is from where the u32 comes from maybe.

The standard open call use standard int: https://man7.org/linux/man-pages/man2/open.2.html
Similarly Rust: https://doc.rust-lang.org/std/os/unix/fs/trait.OpenOptionsExt.html#tymethod.custom_flags
Also fuse expose them as int: http://libfuse.github.io/doxygen/structfuse__file__info.html

I mean, it would be just more convenient for my use case, but it is not that big of an issue, not at all.

**Comment by cberner** [comment]
Ah yes, I see. I'm going to leave it alone for now, but I have an issue open to review all of the usage of signed vs unsigned, as I know there are other inconsistencies which matter: https://github.com/cberner/fuser/issues/65

**Comment by siscia** [comment]
No problem, I just found this (maybe) inconsistency and I waited to point it out!

I close this!

**Comment by cberner** [comment]
Re-opening this. I looked into it more and libfuse treats the value as signed, even though its specified as unsigned in the kernel :thinking: 

https://github.com/libfuse/libfuse/blob/ba3b225a126ebb3c6d4fe27c9f7c73aa4167001e/include/fuse_common.h#L46

I'll address this as part of #65

**Comment by siscia** [comment]
Thanks for listening to my feedback :)
