### ISSUE TITLE
Make capabilities configurable in init()

### ISSUE THREAD

**Issue by cberner** [cberner/fuser#91]
- [x] FUSE_ASYNC_READ
- [x] FUSE_POSIX_LOCKS
- [x] FUSE_FILE_OPS
- [x] FUSE_ATOMIC_O_TRUNC
- [x] FUSE_EXPORT_SUPPORT
- [x] FUSE_BIG_WRITES
- [x] FUSE_DONT_MASK
- [x] FUSE_SPLICE_WRITE
- [x] FUSE_SPLICE_MOVE
- [x] FUSE_SPLICE_READ
- [x] FUSE_FLOCK_LOCKS
- [x] FUSE_HAS_IOCTL_DIR
- [x] FUSE_AUTO_INVAL_DATA
- [x] FUSE_DO_READDIRPLUS
- [x] FUSE_READDIRPLUS_AUTO
- [x] FUSE_ASYNC_DIO
- [x] FUSE_WRITEBACK_CACHE
- [x] FUSE_NO_OPEN_SUPPORT
- [x] FUSE_PARALLEL_DIROPS
- [x] FUSE_HANDLE_KILLPRIV
- [x] FUSE_POSIX_ACL
- [x] FUSE_ABORT_ERROR
- [x] FUSE_MAX_PAGES
- [x] FUSE_CACHE_SYMLINKS
- [x] FUSE_NO_OPENDIR_SUPPORT
- [x] FUSE_EXPLICIT_INVAL_DATA

**Comment by wmanley** [comment]
Regarding init: I've got some plans to use the typestate pattern to simplify this. The idea is that Init is then no longer a callback, but is a function instead. That way the filesystem callback no longer needs to contain state like `is_initialised` or do any synchronisation around that. So we'd have a type like:

```rust
pub struct ChannelNeedsInit{
    chan: Channel,
    init_msg: op::Init
};
impl ChannelNeedsInit {
    fn init(self, capabilities: u32, ...) -> Channel {
        ...
    }
}
```

Usage:

```rust
let (mount, chan_needs_init) = create_mount("/my/mountpoint");
if chan_needs_init.abi_version() > (7, 19) {
    // Blah blah
}
let chan = chan_needs_init.init(my_capabilities, abi_version, ...);
serve_sync(chan, handler);
```

I've not yet started implementation of this though. I guess it would serve some of the same purpose as `Session`, but it would not be parametrized on the `Filesystem`/`Handler` type, nor own the `Mount`.
